name: Publish Docs to confluence
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Publish
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Install Markdown2Confluence
        run: curl -LO https://github.com/justmiles/go-markdown2confluence/releases/download/v3.0.2/markdown2confluence_3.0.2_linux_x86_64.tar.gz
        run: tar -xzvf markdown2confluence_3.0.2_linux_x86_64.tar.gz -C /usr/local/bin/ markdown2confluence
      # This step prints an output (time) from the previous step's action.
      - name: Publish documentation
        env: # Or as an environment variable
          CONFLUENCE_ENDPOINT: ${{ secrets.CONFLUENCE_ENDPOINT }}
          CONFLUENCE_PASSWORD: ${{ secrets.CONFLUENCE_PASSWORD }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
        run: markdown2confluence --space 'WD' --parent 'API Docs' includes/iam/_index.md
